# Site settings
title: Kofi's Blog
email: taichobill@gmail.com
description: >
   To attain knowledge, add things
   everyday. To attain wisdom, 
   remove things every day 
   - Lao Tzu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dakbill.github.io" # the base hostname & protocol for your site
twitter_username: dakbill
github_username:  dakbill


# Build settings
markdown: kramdown
